---
title: "scCART-Cluster Comparison"
author:
  - name: Mercedes Guerrero-Murillo
    email: mguerrero@carrerasresearch.org
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  markdown: 
    wrap: 72
---

```{r working dir, message=FALSE}
# Set the working directory to the project folder. 
project_folder<-"."
setwd(project_folder)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,message = FALSE, tidy = TRUE)
opts_knit$set(root.dir =project_folder )
```

```{r load packages, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(dplyr)
library(sccomp)
library(ggforce)
```

# IP populations

## CAR +/-

```{r ,message=FALSE, warning=FALSE}
integrated.obj<-readRDS("integrated.obj.rds")

integrated.obj <- subset(x = integrated.obj, subset = Timepoint == "IP")
all.genes <- rownames(integrated.obj)
integrated.obj_Scaled <- integrated.obj

integrated.obj <- integrated.obj_Scaled

integrated.obj$cell_group = Idents(integrated.obj)
integrated.obj$sample = paste0(integrated.obj$Class1, integrated.obj$Patient_id)
integrated.obj$type = integrated.obj$Class1

res = integrated.obj |> 
  sccomp_glm( formula_composition = ~ type, 
              formula_variability = ~ 1, 
              percent_false_positive = 5, 
              .sample = sample, 
              .cell_group = cell_group)

plots = plot_summary(res) 

plots$boxplot
```

# CD4/8

## CAR +/-

```{r , fig.height=10, fig.width=12, message=FALSE, warning=FALSE}
rm(list = setdiff(ls(), "integrated.obj_Scaled"))

integrated.obj <- integrated.obj_Scaled
integrated.obj$ProjecTILs[is.na(integrated.obj$ProjecTILs)] <-"Unclassified"
integrated.obj$cell_group = integrated.obj$ProjecTILs
integrated.obj$sample = paste0(integrated.obj$Class1, integrated.obj$Patient_id)
integrated.obj$type = integrated.obj$Class1

res = integrated.obj |> 
  sccomp_glm( formula_composition = ~ type, 
              formula_variability = ~ 1, 
              percent_false_positive = 5, 
              .sample = sample, 
              .cell_group = cell_group)

plots = plot_summary(res) 

plots$boxplot

```

# Session Info

```{r}
sessionInfo()
```

