---
title: "scCART-CompareCAR+/-_IP "
author:
  - name: Mercedes Guerrero-Murillo
    email: mguerrero@carrerasresearch.org
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 

  markdown: 
    wrap: 72
---

```{r working dir, message=FALSE}
# Set the working directory to the project folder. 
project_folder <- "."
setwd(project_folder)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE)
opts_knit$set(root.dir =project_folder )
```

```{r load packages, message=FALSE, warning=FALSE}
library(ggplot2)
library(Seurat)
library(data.table)
library(dplyr)
library(RColorBrewer)
library(VennDiagram)
library(ggrepel)
library(clusterProfiler)
library(org.Hs.eg.db)
library(EnhancedVolcano)
```

# Compare CAR+ vs CAR- 

## IP

```{r CAR+vsCAR-IP, fig.height=8, fig.width=12, message=FALSE}
# Load data
integrated.obj<-readRDS("integrated.obj.rds")

# Filter by IP
integrated.obj.IP <- subset(x = integrated.obj, subset = Timepoint == "IP")
all.genes <- rownames(integrated.obj.IP)
integrated.obj.IP <- ScaleData(integrated.obj.IP, features = all.genes)
Idents(integrated.obj.IP) <- integrated.obj.IP$Class1

DEG <- FindMarkers(integrated.obj.IP, ident.1 = c("CAR+"), ident.2 = c("CAR-"), verbose = FALSE, min.pct = -Inf, logfc.threshold = -Inf, min.cells.feature = 1, min.cells.group = 1)

EnhancedVolcano(DEG ,rownames(DEG),x ="avg_log2FC",y ="p_val_adj",pCutoff = 0.05 ,FCcutoff = 0.5,xlim = c(-2,2),drawConnectors = TRUE)

# GSEA
DEG$clus<- ifelse(DEG$avg_log2FC > 0, "CAR+","CAR-")
DEG$avg_log2FC <-abs(DEG$avg_log2FC)

top100 <- DEG %>% group_by(clus) %>% top_n(n = 100, wt = avg_log2FC)
top100pval <- subset(top100, rowSums(top100[5] < 0.05) > 0)

DEG$gene<- rownames(DEG)
dfsample <- split(DEG$gene,DEG$clus)

dfsample$`CAR+` = bitr(dfsample$`CAR+`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
dfsample$`CAR-` = bitr(dfsample$`CAR-`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")

#do the same here, a line like below for each cluster
genelist <- list("CAR+" = dfsample$`CAR+`$ENTREZID, 
                 "CAR-" = dfsample$`CAR-`$ENTREZID)
GOclusterplot <- compareCluster(geneCluster = genelist, fun = "enrichGO", ont = "BP",OrgDb = "org.Hs.eg.db")
DT::datatable(summary(GOclusterplot))
dotplot(GOclusterplot,showCategory=10)

KEGGclusterplot <- compareCluster(geneCluster = genelist, fun = "enrichKEGG")
DT::datatable(summary(KEGGclusterplot))
dotplot(KEGGclusterplot,showCategory=10)
```

# Session Info

```{r}
sessionInfo()
```
