---
title: "scCART-Heatmap Dotplot"
author:
  - name: Mercedes Guerrero-Murillo
    email: mguerrero@carrerasresearch.org
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 

  markdown: 
    wrap: 72
---

```{r working dir, message=FALSE}
# Set the working directory to the project folder. 
project_folder <- "."
setwd(project_folder)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE)
opts_knit$set(root.dir =project_folder )
```

```{r load packages, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(ggalluvial)
library(grid)
library(forcats)
library(see)
library(dplyr)
library(gghalves)
library(viridis)
library(stringr) 
library(kableExtra)
```

```{r set colors, message=FALSE}
cols2_2 <-c("0 CD8+ Eff mem (EM)" = "#A6CEE3", "1 CD8+ Eff cytotox (Ecyt)" = "#1F78B4","2 Early prolif: HMGN+/HMGB+/PCNA+ cells" = "#B2DF8A","3 CD4+ Naive/SCM" = "#33A02C","4 Early  prolif: MCM3/5/7+ PCNA+ cells" = "#FB9A99","5 Late prolif: histones enriched MKI67+ cells" = "#E31A1C","6 CD4+ Central/Effector memory (CM/EM)" = "#FDBF6F","7 Ribosomal/Mitocondrial/Degradated cells" = "#FF7F00","8 Late prolif: CDK+/CDC+/AURKA+ MIK67+ cells" = "#CAB2D6","9 γδ Tcells" = "#6A3D9A")
```

# Top10 genes

```{r , fig.height=20, fig.width=25, message=FALSE}
integrated.obj<-readRDS("integrated.obj.rds")

markers <- FindAllMarkers(integrated.obj, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10

DoHeatmap(subset(integrated.obj, downsample = 1000), features = unique(top10$gene), group.colors = cols2_2) + NoLegend()

DotPlot(integrated.obj, features =  unique(top10$gene), cols =c("#0610C1", "#C2062F", "#C2062F")) + coord_flip() + RotatedAxis()

FeaturePlot(integrated.obj, features = unique(top10$gene))
```

#  Genes of interest

Genes from the DEG, Pablo selected the most important ones. 

```{r , fig.height=20, fig.width=25, message=FALSE, eval=FALSE}
pablo_markers <-c("CCR7","IL7R","TCF7","CD27","SELL","GZMK","GZMA", "GNLY","GZMH","NKG7","GZMB","PRF1","MCM7","PCNA","CD4","CD8A","CD8B","CD95","MKI67","CDK1","GZMM","HIST1H4C","HIST1H3B","HIST1H1B","HIST1H3C","HIST1H2BF","HIST1H1E","HIST1H3F","HIST1H2AG","HIST1H2AL","HIST1H2BH","MTRNR2L12","MTRNR2L8","RPS2","CCNB1","CCNA2","CCNA1","CDC20","HMGN2","TRDV1","TRGV8")

DoHeatmap(subset(integrated.obj, downsample = 1000), features = unique(pablo_markers)) + NoLegend()
DotPlot(integrated.obj, features =  unique(pablo_markers), cols =c("#0610C1", "#C2062F", "#C2062F")) + coord_flip() + RotatedAxis()
```

# Gamma delta genes

```{r}
gd_markers<-c("ZFP36","CCL4","PRF1","GNLY","NKG7","KLRF1","FCGR3A","TRGV8","TRDV1","TYROBP","GZMA","GZMB","GZMH","GZMK","GZMM","TRDV1","TRGV8")

DoHeatmap(subset(integrated.obj, downsample = 1000), features = unique(gd_markers)) + NoLegend()
DoHeatmap(subset(integrated.obj, downsample = 1000), features = unique(gd_markers)) 
DotPlot(integrated.obj, features =  unique(gd_markers), cols =c("#0610C1", "#C2062F", "#C2062F")) + coord_flip() + RotatedAxis()
```

# Session Info

```{r}
sessionInfo()
```

