---
title: "scCART-Signature Tonic Signaling"
author:
  - name: Mercedes Guerrero-Murillo
    email: mguerrero@carrerasresearch.org
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 

  markdown: 
    wrap: 72
---

```{r working dir, message=FALSE}
# Set the working directory to the project folder.
project_folder <- "."
setwd(project_folder)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE)
```

```{r load packages, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(ggalluvial)
library(grid)
library(forcats)
library(see)
library(dplyr)
library(gghalves)
library(viridis)
library(stringr)
library(RColorBrewer)
library(kableExtra)
library(ggpubr)
library(rstatix)
library(clusterProfiler)
library(EnhancedVolcano)
library(introdataviz)
```

```{r set colors, message=FALSE,tidy = TRUE}
cols1 <- c("0 CD8+ Eff mem (EM)" = "#A6CEE3", "1 CD8+ Eff cytotox (Ecyt)" = "#1F78B4", "3 CD4+ Naive/SCM" = "#33A02C", "6 CD4+ Central/Effector memory (CM/EM)" = "#FDBF6F", "9 γδ Tcells" = "#6A3D9A", "Proliferative cells" = "#F7D764")
cols2 <- c("0 CD8+ Eff mem (EM)" = "#A6CEE3", "1 CD8+ Eff cytotox (Ecyt)" = "#1F78B4", "2 Early prolif: HMGN+/HMGB+/PCNA+ cells" = "#B2DF8A", "3 CD4+ Naive/SCM" = "#33A02C", "4 Early  prolif: MCM3/5/7+ PCNA+ cells" = "#FB9A99", "5 Late prolif: histones enriched MKI67+ cells" = "#E31A1C", "6 CD4+ Central/Effector memory (CM/EM)" = "#FDBF6F", "7 Ribosomal/Mitocondrial/Degradated cells" = "#FF7F00", "8 Late prolif: CDK+/CDC+/AURKA+ MIK67+ cells" = "#CAB2D6", "9 γδ Tcells" = "#6A3D9A")
cols3 <- c("CAR+" = "#66c2a5", "CAR-" = "#fc8d62")
cols4 <- c("#264653", "#2a9d8f", "#e9c46a", "#f4a261", "#e76f51")
cols5 <- c("IP" = "#4E6AAB", "Peak" = "#e78ac3")
cols6 <- c("CD4" = "#147D2C", "CD8" = "#F5C936", "Unknown" = "#7f7f7f", "CD4- CD8-" = "#38369A")
cols7 <- c("#F8766D", "#00BA38", "#619CFF")
cols8 <- c("#E69F00FF", "#56B4E9FF", "#009E73FF", "#F0E442FF")
```

# Tonic Signaling 

Joining the genes of activation and exhaustion

```{r , fig.height=10, fig.width=12, message=FALSE}
integrated.obj <- readRDS("integrated.obj.rds")
```

#  Analysis.

Define genes to analyse. 

```{r ,  fig.height=15, fig.width=17, message=FALSE}
tonic_genes <- c("CD28", "CD40LG", "TNFRSF4", "TNFRSF9", "CD74", "HLA-DBR1", "NKB1", "ICOS", "CD27", "CD25", "CD69", "TOX", "PDCD1", "LAG3", "TIGIT", "CASP8", "HAVCR2", "CTLA4", "PTPN11", "CD160", "CD244")

integrated.obj <- AddModuleScore(object = integrated.obj, features = list(tonic_genes), name = "Tonic.MGM")

FeaturePlot(integrated.obj, features = tonic_genes)
```
 
# IP
 
```{r , fig.height=15, fig.width=17, message=FALSE}
integrated.obj.Peak <- subset(x = integrated.obj, subset = Timepoint == "IP")

aux_df1 <- data.frame(seurat_clusters = Idents(integrated.obj.Peak), integrated.obj.Peak[[]], FetchData(integrated.obj.Peak, vars = tonic_genes, slot = "data"))
```

Print the average, max and sd for each gene

```{r , fig.height=10, fig.width=12, message=FALSE}
aux_df1 %>%
  group_by(Patient_id, Timepoint, Class1) %>%
  summarise_at(vars(one_of(tonic_genes)), list(mean = mean, max = max, sd = sd)) %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  scroll_box(width = "100%", height = "500px")
```


```{r , fig.height=10, fig.width=12, message=FALSE}
FeaturePlot(integrated.obj, features = "Tonic.MGM1")



# CAR+/CAR-

ggplot(aux_df1, aes(x = fct_reorder(Class1, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = Class1)) +
  geom_violin(scale = "width") +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols3)

# CD4/CD8
aux_df1 <- aux_df1[which(aux_df1$final_criteria != "Unknown"), ]

ggplot(aux_df1, aes(x = fct_reorder(final_criteria, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = final_criteria)) +
  geom_violin(scale = "width") +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols6)

ggplot(aux_df1, aes(x = fct_reorder(Class1, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = final_criteria)) +
  geom_split_violin() +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols6)

ggplot(aux_df1, aes(x = fct_reorder(final_criteria, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = Class1)) +
  geom_split_violin() +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols3)
```


# Peak
 
```{r , fig.height=15, fig.width=17, message=FALSE}
integrated.obj.Peak <- subset(x = integrated.obj, subset = Timepoint == "Peak")

aux_df1 <- data.frame(seurat_clusters = Idents(integrated.obj.Peak), integrated.obj.Peak[[]], FetchData(integrated.obj.Peak, vars = tonic_genes, slot = "data"))
```

Print the average, max and sd for each gene

```{r , fig.height=10, fig.width=12, message=FALSE}
aux_df1 %>%
  group_by(Patient_id, Timepoint, Class1) %>%
  summarise_at(vars(one_of(tonic_genes)), list(mean = mean, max = max, sd = sd)) %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  scroll_box(width = "100%", height = "500px")
```


```{r , fig.height=10, fig.width=12, message=FALSE}
FeaturePlot(integrated.obj, features = "Tonic.MGM1")

# CAR+/CAR-

ggplot(aux_df1, aes(x = fct_reorder(Class1, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = Class1)) +
  geom_violin(scale = "width") +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols3)

# CD4/CD8
aux_df1 <- aux_df1[which(aux_df1$final_criteria != "Unknown"), ]

ggplot(aux_df1, aes(x = fct_reorder(final_criteria, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = final_criteria)) +
  geom_violin(scale = "width") +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols6)
```

# CAR+
 
```{r , fig.height=15, fig.width=17, message=FALSE}
integrated.obj.Peak <- subset(x = integrated.obj, subset = Class1 == "CAR+")

aux_df1 <- data.frame(seurat_clusters = Idents(integrated.obj.Peak), integrated.obj.Peak[[]], FetchData(integrated.obj.Peak, vars = tonic_genes, slot = "data"))
```

Print the average, max and sd for each gene

```{r , fig.height=10, fig.width=12, message=FALSE}
aux_df1 %>%
  group_by(Patient_id, Timepoint, Class1) %>%
  summarise_at(vars(one_of(tonic_genes)), list(mean = mean, max = max, sd = sd)) %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  scroll_box(width = "100%", height = "500px")
```


```{r , fig.height=10, fig.width=12, message=FALSE}
FeaturePlot(integrated.obj, features = "Tonic.MGM1")

# IP/Peak

ggplot(aux_df1, aes(x = fct_reorder(Timepoint, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = Timepoint)) +
  geom_violin(scale = "width") +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols5)

# CD4/CD8
aux_df1 <- aux_df1[which(aux_df1$final_criteria != "Unknown"), ]

ggplot(aux_df1, aes(x = fct_reorder(final_criteria, Tonic.MGM1, .fun = median, .desc = TRUE), y = Tonic.MGM1, fill = final_criteria)) +
  geom_violin(scale = "width") +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("") +
  scale_fill_manual(values = cols6)
```

# Session Info

```{r}
sessionInfo()
```
