---
title: "scCART-Signature Exhaustion to publish"
author:
  - name: Mercedes Guerrero-Murillo
    email: mguerrero@carrerasresearch.org
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 

  markdown: 
    wrap: 72
---

```{r working dir, message=FALSE}
# Set the working directory to the project folder. 
project_folder <- "."
setwd(project_folder)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE)
opts_knit$set(root.dir =project_folder)
```

```{r load packages, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(ggalluvial)
library(grid)
library(forcats)
library(see)
library(dplyr)
library(gghalves)
library(viridis)
library(stringr) 
library(RColorBrewer)
library(kableExtra)
library(ggpubr)
library(rstatix)
library(ReactomePA)
library(clusterProfiler)
library(UCell)
library(EnhancedVolcano)
```

```{r set colors, message=FALSE}
cols1 <-c("0 CD8+ Eff mem (EM)" = "#A6CEE3", "1 CD8+ Eff cytotox (Ecyt)" = "#1F78B4","3 CD4+ Naive/SCM" = "#33A02C","6 CD4+ Central/Effector memory (CM/EM)" = "#FDBF6F","9 γδ Tcells" = "#6A3D9A","Proliferative cells"="#F7D764")
cols2 <-c("0 CD8+ Eff mem (EM)" = "#A6CEE3", "1 CD8+ Eff cytotox (Ecyt)" = "#1F78B4","2 Early prolif: HMGN+/HMGB+/PCNA+ cells" = "#B2DF8A","3 CD4+ Naive/SCM" = "#33A02C","4 Early  prolif: MCM3/5/7+ PCNA+ cells" = "#FB9A99","5 Late prolif: histones enriched MKI67+ cells" = "#E31A1C","6 CD4+ Central/Effector memory (CM/EM)" = "#FDBF6F","7 Ribosomal/Mitocondrial/Degradated cells" = "#FF7F00","8 Late prolif: CDK+/CDC+/AURKA+ MIK67+ cells" = "#CAB2D6","9 γδ Tcells" = "#6A3D9A")
cols3<- c("CAR+"="#66c2a5","CAR-"="#fc8d62") 
cols4 <- c("#264653","#2a9d8f","#e9c46a","#f4a261","#e76f51")
cols5<- c("IP"="#4E6AAB","Peak"="#e78ac3")
cols6<- c("CD4"="#147D2C","CD8"="#F5C936","Unknown"="#7f7f7f", "CD4- CD8-"= "#38369A")
cols7 <- c("#F8766D","#00BA38", "#619CFF")
cols8 <- c("#E69F00FF", "#56B4E9FF", "#009E73FF", "#F0E442FF")
```

# Exhaustion

```{r , fig.height=10, fig.width=12, message=FALSE}
integrated.obj<-readRDS("integrated.obj.rds")
```

#  Analysis


```{r , fig.height=10, fig.width=12, message=FALSE}
exhaustion_genes <-  c("TOX", "PDCD1", "LAG3", "TIGIT", "CASP8", "HAVCR2", "CTLA4","PTPN11","CD160","CD244")
# "JAK1","STAT1"
integrated.obj <- AddModuleScore(object = integrated.obj, features = list(exhaustion_genes), name="Exh.MGM")
```

```{r , fig.height=15, fig.width=17, message=FALSE}
FeaturePlot(integrated.obj, features = exhaustion_genes)
```
 
# IP
 
# Published signatures

```{r , fig.height=10, fig.width=12, message=FALSE}

Yost.markers<- read.csv("bcc_tcell_top100_markers_Yost_et al.txt", sep = "\t")

Yost.markers2 <- Yost.markers[Yost.markers$cluster=="CD8_ex",]

signatures <- list(Exhausted_Wherry_2007 = c("AARD","ACADVL","ACKR3","ADAM7","ADCY6","ADGRG1","AFP","AHR","ALCAM","ALOXE3","ANXA3","AOPEP","APOBEC2","ART1","ATP5IF1","ATP5MF","AUH","BAAT","BCL2L11","BCL3","BLK","BTK","CANX","CCDC28B","CCDC93","CCR6","CCRL2","CD22","CD244","CELA1","CELF4","CEP250","CFH","CFHR2","CISH","CKMT1B","CKMT2","CLIC4","COCH","CORO2B","CRYZ","CSF1","CSRP1","CTSE","CUBN","CXCR2","CXCR5","CYTH3","DDIT4","DHRS7B","DLG3","DOCK7","DPP7","EEA1","EFNB3","EGR2","ELK1","ENTPD1","EOMES","EPCAM","ERCC5","ETV1","FAM171A1","FAM207A","FASLG","FKBP10","FLNA","FLT3","FSTL1","GAMT","GAPDHS","GATA1","GCM2","GCSAM","GDNF","GPD2","GPM6B","GRIA1","GRM8","GSX1","GTF3C4","GZMB","H1-4","H1-5","HAO2","HIF1A","HLA-DMA","HMGA2","HOXB8","HOXC6","HOXD10","HSD3B7","HSPA4L","IFI27L2","IFIH1","IL10","IL1A","IL1RN","IMMT","ITGAV","KCNAB1","KCNU1","KCTD9","KHK","KRT27","LAMC1","LAT2","LCLAT1","LGMN","LHPP","LITAF","LRP10","LY75","LY86","MAP2","MC5R","MCAM","MFHAS1","MKI67","MMP14","MRPL48","MRPS2","MS4A1","MYCL","MYO6","MYRF","NAB2","NAT2","NDUFB4","NDUFS4","NEFH","NELFE","OSMR","PARP1","PAWR","PERP","PLA2R1","PLOD3","PLSCR1","POLR2C","PRDM1","PRL","PROX1","PRR15","PRRC1","PTCH1","PTMS","PTPN11","PTPRA","PTPRJ","RGS16","RPRD1B","RPS14","RUNX1T1","SAPCD1","SCGB1A1","SCN7A","SEC14L1","SELP","SFRP2","SGO1","SHMT2","SLC27A4","SLC3A1","SLC4A7","SLC4A8","SPIC","SPOCK1","SPOCK2","SPRR2A","ST6GALNAC2","STRA6","SURF4","SYPL1","TBL1X","TCF7L1","TERF1","TFDP1","TG","THEG","TLN1","TLR7","TM4SF1","TMEM150A","TMEM214","TMEM266","TNFRSF4","TWSG1","VAMP5","VMP1","VNN1","WDR55","WFS1","WIZ","WNK2","XCR1","YAP1","ZNF292","ZNF35","ZNF821"),
                  Exhausted_Carmona_2019 = c("CCL3","TNFRSF9","RGS16","DUT","PRF1","MT1A","CCL4","TIGIT","PDCD1","ANXA2","TNFRSF4","LAG3","SAMSN1","RGS2","TOX","BHLHE40","STMN1","RPS27L","LITAF","TXN","HAVCR2","HILPDA","NR4A2","2810417H13RIK","CASP3","SERPINA3","IL2RB","PGLYRP1","NAP1L1","CENPA","COX17","IRF8","PLEK","NRGN","SH2D2A","CTLA4","STAT3","HSP90B1","MMD","CDK6","IFNG","AA467197","CST7","SERPINB6","GZMB","UHRF2","HIST1H2AP","RBPJ","HMGB1","S100A4","VAMP8","TPI1","BCL2A1","RAN","NRP1","VIM","GPR65","CKS1B","LAT2","D16ERTD472E","HNRNPA1","CDKN2A","HMGN2","FABP5","PGK1","IL10RA","LILRB4A","CYCS","SLC16A11","SNRPD1","SDF4","PLP2","CXCR6","CALR","ITGAV","GLPeakR1","GPD2","CCRL2","NDUFB8","ADAM8","RANBP1","SIVA1","CALM3","DBI","ATP5PF","GM10282","2310031A07RIK","SEC11C","GLDC","SERPINB9","ARSB","ATP5IF1","ID2","KLRD1","PLAC8","CISD1","ACADL","CD74","PGAM1"), Exhausted_Yost_2019 = Yost.markers2$gene, exhaustion_genes =  c("TOX", "PDCD1", "LAG3", "TIGIT", "CASP8", "HAVCR2", "CTLA4","PTPN11","CD160","CD244"),Markers_exhaustion = c("PDCD1", "LAG3", "HAVCR2", "KLRG1", "TIGIT", "CD244", "CD160", "BTLA", "CTLA4", "ENTPD1", "ID2"))

integrated.obj.IP <- subset(x = integrated.obj, subset = Timepoint == "IP")

integrated.obj.IP<- AddModuleScore_UCell(integrated.obj.IP, features = signatures)
featnames <- paste0(names(signatures), "_UCell")
DotPlot(integrated.obj.IP, features = featnames, group.by = "Patient_id",cols = "RdBu") + 
  theme(text = element_text(size = 18), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlab("") + ylab("")

DotPlot(integrated.obj.IP, features = featnames, group.by = "Patient_id",cols = "RdBu") + 
  theme(text = element_text(size = 18), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlab("") + ylab("")

# New plots
integrated.obj.IP$Pt_CAR<- paste(integrated.obj.IP$Patient_id, integrated.obj.IP$Class1, sep="_")

DotPlot(integrated.obj.IP, features = featnames, group.by = "Pt_CAR",cols = "RdBu") + 
  theme(text = element_text(size = 18), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlab("") + ylab("")

integrated.obj.IP$Pt_CD<- paste(integrated.obj.IP$Patient_id, integrated.obj.IP$final_criteria, sep="_")

DotPlot(subset(integrated.obj.IP, final_criteria!= "Unknown") , features = featnames, group.by = "Pt_CD",cols = "RdBu") + 
  theme(text = element_text(size = 18), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlab("") + ylab("")

DotPlot(integrated.obj.IP, features = featnames, group.by = "Class1",cols = "RdBu",scale=FALSE) + 
  theme(text = element_text(size = 18), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlab("") + ylab("")
```

# Session Info

```{r}
sessionInfo()
```



