---
title: "scCART-gammaDelta"
author:
  - name: Mercedes Guerrero-Murillo
    email: mguerrero@carrerasresearch.org
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  markdown: 
    wrap: 72
---

```{r working dir, message=FALSE}
# Set the working directory to the project folder.
project_folder <- "."
setwd(project_folder)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE)
opts_knit$set(root.dir = project_folder)
```

```{r load packages, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(ggalluvial)
library(grid)
library(forcats)
library(see)
library(dplyr)
library(gghalves)
library(viridis)
library(stringr)
library(kableExtra)
```


# Load data

```{r , fig.height=10, fig.width=12, message=FALSE}
integrated.obj <- readRDS("integrated.obj.rds")
```

# gamma delta genes feature plot

```{r , fig.height=20, fig.width=25, message=FALSE}
gammadelta_genes <- c("GZMA", "GZMB", "GZMH", "GZMK", "GZMM", "PRF1", "GNLY", "NKG7", "CD4", "CD8A", "CD8B", "TRDV1", "TRGV8", "TRG", "TRD")

FeaturePlot(integrated.obj, features = gammadelta_genes, cols = c("#d3d3d3", "#bf1b2cff"))
```


```{r , fig.height=10, fig.width=12, message=FALSE}
metadata <- integrated.obj[[]]
metadata$Clusters <- Idents(integrated.obj)
metadata <- metadata[metadata$Class1 == "CAR+", ]

g1 <- ggplot(metadata[metadata$Clusters == "9 Tcells", ], aes(x = Timepoint, fill = Timepoint)) +
  geom_bar() +
  theme_classic()
g1

g2 <- ggplot(metadata[metadata$Clusters == "9 Tcells", ], aes(x = Patient_id, fill = Timepoint)) +
  geom_bar(position = position_dodge(preserve = "single")) +
  theme_classic()
g2
```

#CustomHeatmap

```{r , fig.height=20, fig.width=25, message=FALSE}
gens_gammadelta <- c("ZFP36", "CCL4", "PRF1", "GNLY", "NKG7", "KLRF1", "FCGR3A", "TRGV8", "TRDV1", "TYROBP", "GZMA", "GZMB", "GZMH", "GZMK", "GZMM", "TRDV1", "TRGV8")
DoHeatmap(integrated.obj, features = gens_gammadelta) + NoLegend()
```

# Session Info

```{r}
sessionInfo()
```
